type User {
    ID: ID
    Name: String
    Email: String
    Groups: [String]
}

type Credential {
    token: String
}

input UserInput {
    Name: String!
    Email: String!
    Password: String!
}
