version: '3'

services:
    texas-api:
        container_name: texas-api
        build:
            context: ./texas
            dockerfile: ./texas/apps/texas-server/Dockerfile
            args:
            - API_PORT
            - AUTH_SECRET
        ports:
        - $API_PORT:$API_PORT
        - 5555:5555
        - 5556:5556
        
        volumes:
        - ./texas:/app
        - $RUNTIME/data:/data

        - /app/node_modules
        - /app/apps/texas-server/node_modules
        - /app/apps/texas-cli/node_modules
        - /app/lib/texas-js/node_modules
        - /app/lib/texas-utils/node_modules
        - /app/lib/texas-gql/node_modules
        stdin_open: true
        tty: true
        command: npm start
    
   